### ISSUE TITLE
getting runtime error on Manjaro

### ISSUE THREAD

**Issue by jensMF** [alamminsalo/orion#192]
I get this error-message when I try to start orion (I tried both version from AUR and built it myself):

`qt5ct: using qt5ct plugin`
`Selected default network configuration`
`[1]    16945 segmentation fault (core dumped)  ./orion`

so I built it myself with debug option and ran it with gdb, the output is:

```Starting program: /home/jmf/orion/build/orion 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffcdecf700 (LWP 24226)]
qt5ct: using qt5ct plugin
[New Thread 0x7fffc3d36700 (LWP 24227)]
[New Thread 0x7fffc2935700 (LWP 24228)]
[New Thread 0x7fffc1ef2700 (LWP 24229)]
[New Thread 0x7fffc103b700 (LWP 24230)]
[New Thread 0x7fffc083a700 (LWP 24231)]
Selected default network configuration

Thread 1 "orion" received signal SIGSEGV, Segmentation fault.
0x00007ffff53b535b in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) () from /usr/lib/libQt5Core.so.5```

could someone give me a hint, how to solve this, please?

**Comment by ahjolinna** [comment]
It seems qt5ct is the problem, could you try to run orion in gdb with the debugging command line option : -d / -debug

gdb orion
run - d

And when it crashes : bt full

_Sent from my Sony F5121 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jensMF** [comment]
Here is the full backtrace:
```
#0  0x00007ffff53b535b in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) () at /usr/lib/libQt5Core.so.5
#1  0x00007ffff53b76c4 in QObjectPrivate::connectImpl(QObject const*, int, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff53b79d2 in QObject::connectImpl(QObject const*, void**, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) () at /usr/lib/libQt5Core.so.5
#3  0x0000000000411a0f in QObject::connect<void (RunGuard::*)(), void (QWindow::*)()>(QtPrivate::FunctionPointer<void (RunGuard::*)()>::Object const*, void (RunGuard::*)(), QtPrivate::FunctionPointer<void (QWindow::*)()>::Object const*, void (QWindow::*)(), Qt::ConnectionType) (type=Qt::AutoConnection, slot=(void (QWindow::*)(QWindow * const)) 0x7ffff6502e20 <QWindow::show()>, receiver=0x20, signal=(void (RunGuard::*)(RunGuard * const)) 0x4827b0 <RunGuard::anotherProcessTriggered()>, sender=0x7fffffffdca0) at /usr/include/qt/QtCore/qobject.h:259
        types = 0x0
        app = <incomplete type>
        appIcon = {d = 0x9a5090}
        engine = <incomplete type>
        guard = 
              {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff57dea40 <QObject::staticMetaObject>, stringdata = 0x51ca00 <---Type <return> to continue, or q <return> to quit---
call = 0x4827c0 <RunGuard::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, key = {static null = {<No data fields>}, d = 0xa420f0}, memLockKey = {static null = {<No data fields>}, d = 0xa42410}, sharedmemKey = {static null = {<No data fields>}, d = 0xa42490}, timer = 0x986390, sharedMem = <incomplete type>, memLock = {d = {d = 0xa3f100}}}
        parser = {d = 0xa3f6a0}
        debugOption = {d = {d = 0xa43420}}
        showDebugOutput = <optimized out>
        screens = <optimized out>
        maxDevicePixelRatio = 1
        notificationManager = <optimized out>
        rootContext = <optimized out>
        rootWin = 0x20
#4  0x0000000000411a0f in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:168
        app = <incomplete type>
        appIcon = {d = 0x9a5090}
        engine = <incomplete type>
        guard = 
              {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff57dea40 <QObject::staticMetaObject>, stringdata = 0x51ca00 <qt_meta_stringdata_RunGuard>, data = 0x51c980 <qt_meta_data_RunGuard>, static_metacall = 0x4827c0 <RunGuard::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, key = {static null = {<No data fields>}, d = 0xa420f0}, memLockKey = {static null = {<No data fields>}, d = 0xa42410}, sharedmemKey = {static null = {<No data fields>}, d = 0xa42490}, timer = 0x986390, sharedMem = <incomplete type>, memLock = {d = {d = 0xa3f100}}}
        parser = {d = 0xa3f6a0}
        debugOption = {d = {d = 0xa43420}}
        showDebugOutput = <optimized out>
        screens = <optimized out>
        maxDevicePixelRatio = 1
        notificationManager = <optimized out>
        rootContext = <optimized out>
        rootWin = 0x20
```

**Comment by jensMF** [comment]
I found out the problem. qt5-graphicaleffects has to be installed.
