### ISSUE TITLE
QT_AUTO_SCREEN_SCALE_FACTOR has been deprecated in >=Qt Gui 5.14 

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#286]
https://wiki.qt.io/New_Features_in_Qt_5.14

> Added the QT_ENABLE_HIGHDPI_SCALING environment variable which enables high-dpi scaling based on display DPI. Replaces QT_AUTO_SCREEN_SCALE_FACTOR (now deprecated), and corresponds to the Qt::AA_EnableHighDpiScaling application attribute.

havent checked if this affects qml also yet, but just in case

**Comment by esotericDisciple** [comment]
Is this why Orion crashes when it tries to resize/add new stuff in the UI?
```
Warning: Icon theme "ubuntu-mono-dark" not found. ((null):0, (null))
[New Thread 0x7fffde1ed700 (LWP 32035)]
[New Thread 0x7fffdd9ec700 (LWP 32036)]
[New Thread 0x7fffca28d700 (LWP 32038)]
[New Thread 0x7fffc9a8c700 (LWP 32039)]
[New Thread 0x7fffc928b700 (LWP 32040)]
[New Thread 0x7fffc8a8a700 (LWP 32041)]
[New Thread 0x7fffb7fff700 (LWP 32042)]
[New Thread 0x7fffb6605700 (LWP 32043)]
[New Thread 0x7fffb5e04700 (LWP 32044)]
[New Thread 0x7fffb5603700 (LWP 32045)]
[New Thread 0x7fffb4e02700 (LWP 32046)]
[New Thread 0x7fffa3fff700 (LWP 32047)]
malloc(): invalid size (unsorted)

Thread 12 "QSGRenderThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb7fff700 (LWP 32042)]
0x00007ffff5b26f25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5b26f25 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff5b10897 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5b6a258 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff5b7177a in  () at /usr/lib/libc.so.6
#4  0x00007ffff5b746c4 in _int_malloc () at /usr/lib/libc.so.6
#5  0x00007ffff5b75fc9 in malloc () at /usr/lib/libc.so.6
#6  0x00007ffff6c4904b in QImageData::create(QSize const&, QImage::Format) () at /usr/lib/libQt5Gui.so.5
#7  0x00007ffff6c4918d in QImage::QImage(QSize const&, QImage::Format) () at /usr/lib/libQt5Gui.so.5
#8  0x00007ffff6c491ca in QImage::QImage(int, int, QImage::Format) () at /usr/lib/libQt5Gui.so.5
#9  0x00007ffff6c4a13c in QImage::copy(QRect const&) const () at /usr/lib/libQt5Gui.so.5
#10 0x00007ffff6c4a6a5 in QImage::detach() () at /usr/lib/libQt5Gui.so.5
#11 0x00007ffff6c4be7b in QImage::setColor(int, unsigned int) () at /usr/lib/libQt5Gui.so.5
#12 0x00007fffe9246968 in  () at /usr/lib/libQt5XcbQpa.so.5
#13 0x00007ffff6f160de in QTextureGlyphCache::textureMapForGlyph(unsigned int, QFixed) const () at /usr/lib/libQt5Gui.so.5
#14 0x00007ffff6fa6bfe in QOpenGLTextureGlyphCache::fillTexture(QTextureGlyphCache::Coord const&, unsigned int, QFixed) () at /usr/lib/libQt5Gui.so.5
#15 0x00007ffff6f17dd5 in QTextureGlyphCache::fillInPendingGlyphs() () at /usr/lib/libQt5Gui.so.5
#16 0x00007ffff736c6d1 in  () at /usr/lib/libQt5Quick.so.5
#17 0x00007ffff73682eb in  () at /usr/lib/libQt5Quick.so.5
#18 0x00007ffff743d1ce in QQuickTextNode::addGlyphs(QPointF const&, QGlyphRun const&, QColor const&, QQuickText::TextStyle, QColor const&, QSGNode*) () at /usr/lib/libQt5Quick.so.5
#19 0x00007ffff7442679 in  () at /usr/lib/libQt5Quick.so.5
#20 0x00007ffff743e231 in QQuickTextNode::addTextLayout(QPointF const&, QTextLayout*, QColor const&, QQuickText::TextStyle, QColor const&, QColor const&, QColor const&, QColor const&, int, int, int, int) () at /usr/lib/libQt5Quick.so.5
#21 0x00007ffff743ca5f in QQuickText::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*) () at /usr/lib/libQt5Quick.so.5
#22 0x00007ffff73e1d58 in QQuickWindowPrivate::updateDirtyNode(QQuickItem*) () at /usr/lib/libQt5Quick.so.5
#23 0x00007ffff73e261c in QQuickWindowPrivate::updateDirtyNodes() () at /usr/lib/libQt5Quick.so.5
#24 0x00007ffff73e3d42 in QQuickWindowPrivate::syncSceneGraph() () at /usr/lib/libQt5Quick.so.5
#25 0x00007ffff7384305 in  () at /usr/lib/libQt5Quick.so.5
#26 0x00007ffff73863a4 in  () at /usr/lib/libQt5Quick.so.5
#27 0x00007ffff738a7b7 in  () at /usr/lib/libQt5Quick.so.5
#28 0x00007ffff5f7ffc6 in  () at /usr/lib/libQt5Core.so.5
#29 0x00007ffff41194cf in start_thread () at /usr/lib/libpthread.so.0
#30 0x00007ffff5bea2d3 in clone () at /usr/lib/libc.so.6
```

**Comment by ahjolinna** [comment]
works for me on arch and openSUSE, have you tried a rebuild?

**Comment by esotericDisciple** [comment]
Will try to see if a rebuild fixes that, but before it wouldn't always crash after left-button-pressing over a followed  channel icon
